language: java
jdk: openjdk8

branches:
 only:
  - master
  - dev

cache:
 directories:
  - $HOME/.m2
  
# Override default install or it fails because it runs everything without running tests  
install: mvn clean

addons:
  sonarcloud:
    organization: "nbrest"
    token:
      secure: "QppkpaRLeG7HCJg8+pMTZOWIkL9ciw94+daFvb1cMk4pKkakl8GTAS64E7HQN39eGqN3RZItCDUSOzQ9th1C/vxJ+amwLmWQlxutD5508WFFjk5YjMST70MCVP9HaIlr0tqr1/NCGg7V707rHi8jg3ICCXRltxQMx9mW3jG9wNt7t7ELBwb0gavFFICVfnsLNZfA/acXUqapZyUOt+dCwr/Jcslb+nqfAeRE6srq3Iiaam2M1SOfEm6bvyHX7UYNEXY+YRUvss/RC3DPXsf73LyaVEAiRYjEvOo78gOvRPe1x6PHF3autoUOE7xSJVGon14WxuHFOcDCNi54zi3F4X2EDIqgP4LdAZxizzNZKbmhTjZYUMBXU1MtcAl0V9s02gczDK3wRfrQDAE3FpCqR7yH2BcEzuUgeLmk4LAYLNUtPC+VE0J2UZZV5Rr/RpmRCyRYxS80Nu7szjRiwxCdTBChJiEkrK2dsGjNRnvlVj4+4gTYrLUY33AEoSP6uXW+Vwbv8yOGEUoI2qzZgQDyxsgl3rmlET31PN1yvPvdfUInpf9xfN35ivGE66iCZZB0Eze/gjyv445T/CYqiGUUBVDaqfCagbkqRMBBimn67p9zpiqvcPHqjSLxpenpj2gwHFgC1WXVtebyplYGBdKY8f5WELR8eTYgZfkCVfDqsFo="

script:
  # the following command line builds the project, runs the tests with coverage and then execute the SonarCloud analysis
  #- mvn clean org.jacoco:jacoco-maven-plugin:prepare-agent install sonar:sonar
  # Using mvn install until the code in master is analyzed in sonarcloud. After that, I can delete mvn install and run the above command
  - mvn install
  
after_success:
 - bash <(curl -s https://codecov.io/bash)  
